server:
  port: 8180
  servlet:
    context-path: /${spring.application.name}

spring:
  devtools:
    restart:
      enabled: true
  cloud:
    consul:
      host: 192.168.1.125
      discovery:
        healthCheckPath: /${spring.application.name}/actuator/health
        healthCheckCriticalTimeout: 60s
        preferIpAddress: true
        tags: foo=bar, baz