apiVersion: v1
kind: Service
metadata:
  name: consumer
  labels:
    run: dubbo-demo-consumer
spec:
  type: ClusterIP
  ports:
  - port: 18080
    targetPort: 18080
    name: rest
  - port: 19090
    targetPort: 19090
    name: jmx-prometheus
  selector:
    run: dubbo-demo-consumer
