server:
  port: 8081
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@
spring:
  profiles:
    active: sit
  application:
    name: book-store-app